vue-cli tasks
js-tasks-ru/vue-20220125_ereminaep127 pull request #4
Opened 2022-02-09 17:06 UTC by ereminaep

2022-02-09 17:07 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-02-12 12:10 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-02-12 17:25 UTC, ShGKme requested changes
В 03-UiDropdown1 некорректно работает дополнительная часть при обновлении значения компонента...

В остальном всё принято

2022-02-12 17:25 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +  },
Если иконка тоже зависит от типа тоста, то это должна быть часть реализации компонента `Toast`, как и класс.

2022-02-12 17:25 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +    }
Здесь хорошо подходит метод some: https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/some

2022-02-12 17:25 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +  },
`currentModelValue`, использующийся для `select`, инициализируется с `modelValue`, но не зависит от него. При изменении `modelValue` снаружи значение в `select` не поменяется, и получится некорректное состояние...

2022-02-13 10:02 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-02-14 20:51 UTC, ShGKme requested changes
В `01-AuthPages` требуется переход в соответствии с query параметром `from`. Остальные задачи приняты.

2022-02-14 20:51 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
>      </button>
`this` в шаблоне не требуется, код в шаблоне выполняется в контексте экземпляре.

2022-02-14 20:51 UTC, ShGKme commented on 05-vue-router/01-AuthPages/views/PageLogin.vue
> +      }
При наличии параметра `this.$route.query.from` переход должен быть именно на него, а не на страницу регистрации.

2022-02-15 17:08 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-02-16 18:32 UTC, ShGKme approved these changes
Все задачи приняты 👍

2022-02-16 18:33 UTC, merged